name: cse_archive
description: CSE Archive web app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  get: ^4.6.6
  go_router: ^11.1.2
  intl: ^0.18.1
  rive: ^0.11.17
  sentry_flutter: ^7.10.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  assets:
    - .env
    - assets/riv/
    - assets/svg/

  fonts:
    - family: icons
      fonts:
        - asset: assets/font/icons.ttf
    - family: peyda
      fonts:
        - asset: assets/font/peyda/peyda-light.ttf
          weight: 300
        - asset: assets/font/peyda/peyda-regular.ttf
          weight: 400
        - asset: assets/font/peyda/peyda-medium.ttf
          weight: 500
        - asset: assets/font/peyda/peyda-semiBold.ttf
          weight: 600
        - asset: assets/font/peyda/peyda-bold.ttf
          weight: 700
